name: Dependencies Check

on:
  # can't schedule here since scheduled jobs always run on main
  workflow_dispatch: {}

jobs:
  find_dependency_cases:
    runs-on: ubuntu-latest

    outputs:
      PYTHON_DEPENDENCY_CASES: ${{ steps.list-python-dependencies.outputs.PYTHON_DEPENDENCY_CASES }}

    steps:
    - uses: actions/checkout@v4
    - uses: samuelcolvin/list-python-dependencies@main
      id: list-python-dependencies
      with:
        mode: first-last

  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.PYTHON_DEPENDENCY_CASE }}

    needs:
    - find_dependency_cases

    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7', '3.11']
        PYTHON_DEPENDENCY_CASE: ${{ fromJSON(needs.find_dependency_cases.outputs.PYTHON_DEPENDENCY_CASES) }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: make install-testing

    - name: uninstall optional deps
      run: pip uninstall -y email-validator devtools python-dotenv

    - run: pip install ${{ matrix.PYTHON_DEPENDENCY_CASE }}

    - run: pip freeze

    - run: make test
